export type MenuItem = {
  id: string;
  name: string;
  description: string;
  price: number; // numerical price for cart calculation
  priceString: string; // original formatted TZS price
  category: 'cakes' | 'juices' | 'meals' | 'snacks';
  image: string;
  featured?: boolean;
  tags?: string[];
};

export const menuItems: MenuItem[] = [
  // CAKES
  {
    id: 'c1',
    name: 'Chocolate Dream Cake',
    description: 'Rich, moist chocolate cake with premium cocoa ganache and smooth dark frosting.',
    price: 45000,
    priceString: '45,000 TZS',
    category: 'cakes',
    featured: true,
    image: 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=600&h=600&fit=crop',
    tags: ['signature', 'chocolate', 'premium'],
  },
  {
    id: 'c2',
    name: 'Vanilla Cloud Cake',
    description: 'Light, fluffy vanilla layers filled with fresh chantilly cream and berry compote.',
    price: 40000,
    priceString: '40,000 TZS',
    category: 'cakes',
    image: 'https://images.unsplash.com/photo-1563729784474-d77dbb933a9e?w=600&h=600&fit=crop',
    tags: ['classic', 'fresh', 'popular'],
  },
  {
    id: 'c3',
    name: 'Red Velvet Elegance',
    description: 'Velvety crimson layers with a delicate vanilla crumb and luxurious cream cheese whip.',
    price: 50000,
    priceString: '50,000 TZS',
    category: 'cakes',
    featured: true,
    image: 'https://images.unsplash.com/photo-1616541823729-00fe0aacd32c?w=600&h=600&fit=crop',
    tags: ['elegant', 'premium', 'special'],
  },
  {
    id: 'c4',
    name: 'Carrot Cake Delight',
    description: 'Spiced carrot cake layers packed with walnuts, raisins, and finished with smooth cream cheese.',
    price: 42000,
    priceString: '42,000 TZS',
    category: 'cakes',
    image: 'https://images.unsplash.com/photo-1607958996333-41aef7caefaa?w=600&h=600&fit=crop',
    tags: ['spiced', 'classic', 'favorite'],
  },
  {
    id: 'c5',
    name: 'Strawberry Paradise',
    description: 'Fresh strawberry layers infused with wild strawberry reduction and rich whipped cream.',
    price: 48000,
    priceString: '48,000 TZS',
    category: 'cakes',
    featured: true,
    image: 'https://images.unsplash.com/photo-1587314168485-3236d6710814?w=600&h=600&fit=crop',
    tags: ['fresh', 'fruity', 'seasonal'],
  },
  {
    id: 'c6',
    name: 'Lemon Zest Cake',
    description: 'Zesty lemon sponge with citrus soak, tangy curd, and crystalline sugar dusting.',
    price: 38000,
    priceString: '38,000 TZS',
    category: 'cakes',
    image: 'https://images.unsplash.com/photo-1519869325930-281384150729?w=600&h=600&fit=crop',
    tags: ['fresh', 'citrus', 'light'],
  },

  // JUICES
  {
    id: 'j1',
    name: 'Mango Sunrise',
    description: 'Fresh organic mango juice with passion fruit swirls and a splash of lime.',
    price: 8000,
    priceString: '8,000 TZS',
    category: 'juices',
    featured: true,
    image: 'https://images.unsplash.com/photo-1716441392930-b4daa288266a?w=600&h=600&fit=crop',
    tags: ['tropical', 'fresh', 'signature'],
  },
  {
    id: 'j2',
    name: 'Green Vitality Smoothie',
    description: 'Nutritious fusion of spinach, green apple, fresh ginger root, and raw honey.',
    price: 10000,
    priceString: '10,000 TZS',
    category: 'juices',
    image: 'https://images.unsplash.com/photo-1610970881699-44a5587caaec?w=600&h=600&fit=crop',
    tags: ['healthy', 'green', 'energizing'],
  },
  {
    id: 'j3',
    name: 'Berry Blast Juice',
    description: 'Antioxidant-rich blend of fresh strawberries, blueberries, and red grapes.',
    price: 9000,
    priceString: '9,000 TZS',
    category: 'juices',
    featured: true,
    image: 'https://images.unsplash.com/photo-1600271886742-f049cd451bba?w=600&h=600&fit=crop',
    tags: ['fruity', 'antioxidants', 'popular'],
  },
  {
    id: 'j4',
    name: 'Watermelon Refresh',
    description: 'Refreshing cold-pressed watermelon juice garnished with fresh garden mint.',
    price: 7000,
    priceString: '7,000 TZS',
    category: 'juices',
    image: 'https://images.unsplash.com/photo-1589733901241-5e514f29079f?w=600&h=600&fit=crop',
    tags: ['refreshing', 'seasonal', 'light'],
  },
  {
    id: 'j5',
    name: 'Pineapple Paradise',
    description: 'Tenerife pineapple juice blended with coconut cream and ginger spikes.',
    price: 9000,
    priceString: '9,000 TZS',
    category: 'juices',
    image: 'https://images.unsplash.com/photo-1551024709-8f23befc6f87?w=600&h=600&fit=crop',
    tags: ['tropical', 'coconut', 'exotic'],
  },
  {
    id: 'j6',
    name: 'Orange Citrus Blend',
    description: 'Classic freshly squeezed orange juice, served cold with natural honeycomb.',
    price: 6000,
    priceString: '6,000 TZS',
    category: 'juices',
    image: 'https://images.unsplash.com/photo-1621506289937-a8e4df240d0b?w=600&h=600&fit=crop',
    tags: ['citrus', 'vitamin C', 'classic'],
  },

  // MEALS
  {
    id: 'm1',
    name: 'Grilled Chicken Perfection',
    description: 'Marinated half chicken, char-grilled with local spices, served with fragrant basmati.',
    price: 35000,
    priceString: '35,000 TZS',
    category: 'meals',
    featured: true,
    image: 'https://images.unsplash.com/photo-1598515214211-89d3c73ae83b?w=600&h=600&fit=crop',
    tags: ['grilled', 'protein', 'signature'],
  },
  {
    id: 'm2',
    name: 'Tanzanian Ugali & Stew',
    description: 'Traditional fine ground white maize ugali served with rich slow-cooked beef stew.',
    price: 18000,
    priceString: '18,000 TZS',
    category: 'meals',
    image: 'https://images.unsplash.com/photo-1627308595229-7830a5c91f9f?w=600&h=600&fit=crop',
    tags: ['traditional', 'local', 'comfort'],
  },
  {
    id: 'm3',
    name: 'Sukuma Wiki Plate',
    description: 'Sautéed local collard greens with coconut cream, organic beans, and warm chapati.',
    price: 15000,
    priceString: '15,000 TZS',
    category: 'meals',
    image: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?w=600&h=600&fit=crop',
    tags: ['vegetarian', 'local', 'healthy'],
  },
  {
    id: 'm4',
    name: 'Chicken Biryani Special',
    description: 'Highly aromatic basmati rice cooked layered with saffron, rosewater, and spiced chicken.',
    price: 32000,
    priceString: '32,000 TZS',
    category: 'meals',
    featured: true,
    image: 'https://images.unsplash.com/photo-1633945274405-b6c8069047b0?w=600&h=600&fit=crop',
    tags: ['rice', 'chicken', 'aromatic'],
  },
  {
    id: 'm5',
    name: 'Beef Nyama Choma',
    description: 'Tender local beef cubes char-grilled over acacia coal, served with kachumbari.',
    price: 38000,
    priceString: '38,000 TZS',
    category: 'meals',
    featured: true,
    image: 'https://images.unsplash.com/photo-1544025162-d76694265947?w=600&h=600&fit=crop',
    tags: ['grilled', 'beef', 'premium'],
  },
  {
    id: 'm6',
    name: 'Fish Fillet Delight',
    description: 'Pan-seared lake fish fillet finished with lemon-infused butter sauce and herbs.',
    price: 36000,
    priceString: '36,000 TZS',
    category: 'meals',
    image: 'https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?w=600&h=600&fit=crop',
    tags: ['seafood', 'fresh', 'light'],
  },

  // SNACKS
  {
    id: 's1',
    name: 'Samosa Trio',
    description: 'Golden crispy pastry shells filled with spiced local beef and fresh coriander.',
    price: 12000,
    priceString: '12,000 TZS',
    category: 'snacks',
    featured: true,
    image: 'https://images.unsplash.com/photo-1601050690597-df056fb4ce78?w=600&h=600&fit=crop',
    tags: ['crispy', 'traditional', 'popular'],
  },
  {
    id: 's2',
    name: 'Cheese Bread Rolls',
    description: 'Fluffy brioche rolls baked with cheddar stuffing and fresh oregano glazing.',
    price: 10000,
    priceString: '10,000 TZS',
    category: 'snacks',
    image: 'https://images.unsplash.com/photo-1549931319-a545dcf3bc73?w=600&h=600&fit=crop',
    tags: ['bread', 'cheese', 'savory'],
  },
  {
    id: 's3',
    name: 'Chocolate Croissant',
    description: 'Flaky pure butter croissant layered with premium dark Belgian chocolate filling.',
    price: 8000,
    priceString: '8,000 TZS',
    category: 'snacks',
    featured: true,
    image: 'https://images.unsplash.com/photo-1608198093002-ad4e005484ec?w=600&h=600&fit=crop',
    tags: ['pastry', 'chocolate', 'breakfast'],
  },
  {
    id: 's4',
    name: 'Vegetable Spring Rolls',
    description: 'Crispy rice-paper rolls stuffed with finely shredded cabbage, carrots, and sweet chili dip.',
    price: 11000,
    priceString: '11,000 TZS',
    category: 'snacks',
    image: 'https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?w=600&h=600&fit=crop',
    tags: ['vegetarian', 'crispy', 'light'],
  },
  {
    id: 's5',
    name: 'Mandazi Sweet Treats',
    description: 'Traditional cardamom-spiced fried dough, light, airy, and dusted with icing sugar.',
    price: 5000,
    priceString: '5,000 TZS',
    category: 'snacks',
    image: 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?w=600&h=600&fit=crop',
    tags: ['traditional', 'sweet', 'classic'],
  },
  {
    id: 's6',
    name: 'Spinach Pastry',
    description: 'Crisp puff pastry triangle packed with sautéed wild spinach and creamy Greek feta.',
    price: 9000,
    priceString: '9,000 TZS',
    category: 'snacks',
    image: 'https://images.unsplash.com/photo-1541532713592-79a0317b6b77?w=600&h=600&fit=crop',
    tags: ['vegetarian', 'pastry', 'healthy'],
  },
];

export const categories = [
  { id: 'cakes', label: 'Cakes', icon: '🎂' },
  { id: 'juices', label: 'Juices', icon: '🥤' },
  { id: 'meals', label: 'Meals', icon: '🍗' },
  { id: 'snacks', label: 'Snacks', icon: '🍪' },
];

export function getMenuByCategory(category: string): MenuItem[] {
  return menuItems.filter((item) => item.category === category);
}

export function getFeaturedItems(): MenuItem[] {
  return menuItems.filter((item) => item.featured);
}
